# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStampedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ssh_search.TimeStampedModel')),
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('session_id', models.CharField(blank=True, max_length=32, null=True)),
            ],
            bases=('ssh_search.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='SocialLogin',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ssh_search.TimeStampedModel')),
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('auth_token', models.CharField(blank=True, max_length=64, null=True)),
                ('site_name', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ssh_search.SiteUser', to_field='email')),
            ],
            options={
                'ordering': ['user_id'],
            },
            bases=('ssh_search.timestampedmodel',),
        ),
    ]
