# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLogin',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('auth_token', models.CharField(blank=True, max_length=64, null=True)),
                ('site_name', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('session_id', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sociallogin',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssh_search.User', to_field='email'),
        ),
    ]
